import numpy as np
import os, sys, subprocess, glob, json
from pathlib import Path

os.makedirs('logs', exist_ok=True)

rng = np.random.default_rng(seed=666)

# running Locator on Pf7 data
chromosomes = [str(i) if i > 9 else '0'+str(i) for i in np.arange(1, 15)]
training_sets = np.arange(20)
"""

chromosomes=['01']
training_sets=[0]

"""
rule all:
    input: expand( 'predlocs/{chrom}_{ts}_complete.txt', chrom=chromosomes, ts=training_sets )

rule sortdata:
    output: 'pf7_africa_QC.txt'
    conda: 'py39'
    shell: 'python ../scripts/pf7_data_sort.py'

rule make_ts:
    input: 'pf7_africa_QC.txt'
    output: expand( 'training_sets/pf7_ts_{ts}.txt', ts=training_sets )
    conda: 'py39'
    shell: 'python ../scripts/make_empirical_ts.py --metadata {input} --pred_prop 0.05 --out training_sets/pf7_ts'

rule run_locator:
    input:
        gt = 'pf7_genotypes/Pf3D7_{chrom}',
        ts = 'training_sets/pf7_ts_{ts}.txt'
    output: 'predlocs/{chrom}_{ts}_complete.txt'
    conda: 'locating'
    resources:
        #slurm_extra="--partition=gpu2 --gpus=1 --constraint=gpu-10gb --time=6:00:00 --nodes=1 --mem=200G"
        runtime=300,
        partition='gpu2',
        mem_mb=200000,
        gpus=1,
        constraint='gpu-10gb'
    log: 'logs/{chrom}_{ts}.log'
    shell: 
        """
        module load cuda/11.5.1
        python ../../locator/scripts/locator.py --sample_data {input.ts} --zarr {input.gt} --out predlocs/{wildcards.chrom}_{wildcards.ts} --windows --window_size 500000 &> {log}
        """
